project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: floating
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
      - section: "Layout"
        contents:
          
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

