project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: floating
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
      - section: "Interests"
        contents:
          - about.qmd
          - GI.qmd
          
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

